### ISSUE TITLE
Spelling error in ./404.html

### ISSUE THREAD

**Issue by Soham-Wani** [jigar-sable/Portfolio-Website#4]
Not a big mistake, but thought it would be cool to let yo know. In line 44 of https://github.com/jigar-sable/Portfolio-Website/blob/main/404.html, `<p>` tag as errors. 

Original:
```
<div class="msg">
<h3>Look like you're lost</h3>
<p>the page you are looking for not avaible!</p>
```

Suggested:
```
<div class="msg">
<h3>Looks like you're lost</h3>
<p>The page you are looking for is not available!</p>
```

P.S.: Love your work!

**Comment by jigar-sable** [comment]
Thank you for bringing this to my attention! 
I've updated the same.
